# Generated by Django 4.2.16 on 2024-10-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_book_description_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download_file',
            field=models.FileField(default='uploads/default_file.pdf', upload_to='downloads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='uploads/default_file.pdf', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
