# Generated by Django 4.2.16 on 2024-10-06 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 6, 12, 33, 16, 681404, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
